// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: account.sql

package db

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (
  owner,
  balance,
  currency
) VALUES (
  $1, $2, $3
)
RETURNING id, created, code, owner, balance, currency
`

type CreateAccountParams struct {
	Owner    sql.NullString `json:"owner"`
	Balance  sql.NullInt64  `json:"balance"`
	Currency string         `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Owner, arg.Balance, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Code,
		&i.Owner,
		&i.Balance,
		&i.Currency,
	)
	return i, err
}
